apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak-proxy
    spec:
      containers:
      - name: keycloak-proxy
        image: appsoa/docker-centos-openidc
        imagePullPolicy: Always
        volumeMounts:
        - name: keycloak-proxy-config
          mountPath: /config
      volumes:
      - name: keycloak-proxy-config
        secret:
          secretName: keycloak-proxy-config
