---
  kind: Service
  apiVersion: v1
  metadata:
    name: keycloak-proxy
  spec:
    selector:
      app: keycloak-proxy
    ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000
        name: ui
