---
  kind: Service
  apiVersion: v1
  metadata:
    name: keycloak-proxy
  spec:
    selector:
      app: keycloak-proxy
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        name: http
